CadastroVeiculos/CadastroVeiculos.Site/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CadastroVeiculos.Core.DAL;
using CadastroVeiculos.Core.Model;

namespace CadastroVeiculos.Site.Controllers
{
    public class HomeController : Controller
    {
        private CadastroVeiculosContexto db = new CadastroVeiculosContexto();

        public async Task<ActionResult> Index()
        {
            return View(await db.Veiculo.ToListAsync());
        }
    }
}

CadastroVeiculos/CadastroVeiculos.Site/Controllers/VeiculoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CadastroVeiculos.Core.DAL;
using CadastroVeiculos.Core.Model;
using System.IO;

namespace CadastroVeiculos.Site.Controllers
{
    public class VeiculoController : Controller
    {
        private CadastroVeiculosContexto db = new CadastroVeiculosContexto();
        
        // GET: Veiculo
        public async Task<ActionResult> Index()
        {
            return View(await db.Veiculo.ToListAsync());
        }

        // GET: Veiculo/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Veiculo veiculo = await db.Veiculo.FindAsync(id);
            if (veiculo == null)
            {
                return HttpNotFound();
            }
            return View(veiculo);
        }

        // GET: Veiculo/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Veiculo/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Placa,Renavam,NomeProprietario,CPF,Bloqueado")] Veiculo veiculo, IEnumerable<HttpPostedFileBase> files)
        {
            if (ModelState.IsValid)
            {
                db.Veiculo.Add(veiculo);
                await db.SaveChangesAsync();

                foreach (var file in files)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                        var arquivo = Guid.NewGuid() + Path.GetExtension(file.FileName);
                        var pathArquivo = Path.Combine(Server.MapPath("/uploads"), arquivo);
                        file.SaveAs(pathArquivo);

                        VeiculoImagem imagem = new VeiculoImagem() { 
                            IdVeiculo = veiculo.Id,
                            Arquivo = arquivo,
                            Path = pathArquivo
                        };

                        db.VeiculoImagem.Add(imagem);
                        await db.SaveChangesAsync();
                    }
                }

                return RedirectToAction("Index", "Home");
            }

            return View(veiculo);
        }

        // GET: Veiculo/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Veiculo veiculo = await db.Veiculo.FindAsync(id);
            if (veiculo == null)
            {
                return HttpNotFound();
            }
            return View(veiculo);
        }

        // POST: Veiculo/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Placa,Renavam,NomeProprietario,CPF,Bloqueado")] Veiculo veiculo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(veiculo).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(veiculo);
        }

        // GET: Veiculo/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Veiculo veiculo = await db.Veiculo.FindAsync(id);
            if (veiculo == null)
            {
                return HttpNotFound();
            }
            return View(veiculo);
        }

        // POST: Veiculo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Veiculo veiculo = await db.Veiculo.FindAsync(id);
            db.Veiculo.Remove(veiculo);
            await db.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CadastroVeiculos/CadastroVeiculos.Site/Views/Home/Index.cshtml
@model IEnumerable<CadastroVeiculos.Core.Model.Veiculo>

@{
    ViewBag.Title = "Index";
}

<h2>Lista de Veículos</h2>
<h4>cadastrados no sistema</h4>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Bloqueado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Placa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Renavam)
        </th>
        <th>Ações</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="padding-left:30px;">
                @Html.DisplayFor(modelItem => item.Bloqueado)
            </td>
            <td>
                @*@Html.Raw(string.Format("{0}-{1}", item.Placa.Substring(0, 3), item.Placa.Substring(2, 4)))*@
                @Html.DisplayFor(modelItem => item.Placa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Renavam)
            </td>
            <td style="width:250px;">
                @Html.ActionLink("Editar", "Edit", "Veiculo", new { id = item.Id }, new { @class = "btn btn-sm btn-warning" }) 
                @Html.ActionLink("Visualizar", "Details", "Veiculo", new { id = item.Id }, new { @class = "btn btn-sm btn-info" }) 
            </td>
        </tr>
    }

</table>

<p>
    @Html.ActionLink("Cadastrar Veículos", "Create", "Veiculo", null, new { @class = "btn btn-success" })
</p>

CadastroVeiculos/CadastroVeiculos.Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cadastro de Veículos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Sistema de Cadastro e Consulta", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cadastro", "Create", "Veiculo")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/inputmask")
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $(document).ready(function ()
        {
            //$("#Placa").inputmask("mask", { "mask": "AAA-9999" });
            //$("#CPF").inputmask("mask", { "mask": "999.999.999-99" }, { reverse: true });
            //$("#Renavam").inputmask("mask", { "mask": "99999999999" });
            $('#Placa').mask('SSS-0000');
            $('#CPF').mask('000.000.000-00');
            $('#Renavam').mask('00000000-00');
        });
    </script>
</body>
</html>

CadastroVeiculos/CadastroVeiculos.Site/Views/Veiculo/Create.cshtml
@model CadastroVeiculos.Core.Model.Veiculo

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar Veículo</h2>


@using (Html.BeginForm(Html.BeginForm("Create", "Veiculo", null, FormMethod.Post, new { enctype = "multipart/form-data" }))) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Veiculo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="col-md-10">
                @Html.LabelFor(model => model.Placa, htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "form-control", style = "width:160px;" } })
                @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.LabelFor(model => model.Renavam, htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Renavam, new { htmlAttributes = new { @class = "form-control", style = "width:160px;" } })
                @Html.ValidationMessageFor(model => model.Renavam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.LabelFor(model => model.NomeProprietario, htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeProprietario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeProprietario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.LabelFor(model => model.PathImagens, htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col-md-10 editor-field multiple">
                <input id="PathImagens" title="Imagens do Veículo" type="file" class="multiple" name="files" multiple />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.Bloqueado)
                    @Html.LabelFor(model => model.Bloqueado, htmlAttributes: new { @class = "control-label" })
                    @Html.ValidationMessageFor(model => model.Bloqueado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.ActionLink("Voltar", "Index", "Home", null, new { @class = "btn btn-info" })
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CadastroVeiculos/CadastroVeiculos.Site/Views/Veiculo/Delete.cshtml
@model CadastroVeiculos.Core.Model.Veiculo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Veiculo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Placa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Placa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Renavam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Renavam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomeProprietario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeProprietario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CPF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CPF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bloqueado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bloqueado)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CadastroVeiculos/CadastroVeiculos.Site/Views/Veiculo/Details.cshtml
@model CadastroVeiculos.Core.Model.Veiculo

@{
    ViewBag.Title = "Visualizar Dados";
}

<h2>Visualizar Dados</h2>

<div>
    <h4>Veiculo</h4>
    <hr />

    <div>
        @foreach (var item in Model.VeiculoImagem)
        {
            <img src="~/uploads/@item.Arquivo" style="height:200px;width:350px;margin:10px;" />
        }
    </div>

    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Placa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Placa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Renavam)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Renavam)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NomeProprietario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeProprietario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CPF)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CPF)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bloqueado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bloqueado)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Voltar", "Index", "Home", null, new { @class = "btn btn-info" })
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-warning" })
</p>

CadastroVeiculos/CadastroVeiculos.Site/Views/Veiculo/Edit.cshtml
@model CadastroVeiculos.Core.Model.Veiculo

@{
    ViewBag.Title = "Editar";
}

<h2>Editar Dados Veículo</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Veiculo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <div class="col-md-10">
                @Html.LabelFor(model => model.Placa, htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Placa, new { htmlAttributes = new { @class = "form-control", style = "width:160px;" } })
                @Html.ValidationMessageFor(model => model.Placa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.LabelFor(model => model.Renavam, htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Renavam, new { htmlAttributes = new { @class = "form-control", style = "width:160px;" } })
                @Html.ValidationMessageFor(model => model.Renavam, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.LabelFor(model => model.NomeProprietario, htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeProprietario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeProprietario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.LabelFor(model => model.CPF, htmlAttributes: new { @class = "control-label" })
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPF, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CPF, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.Bloqueado)
                    @Html.LabelFor(model => model.Bloqueado, htmlAttributes: new { @class = "control-label" })
                    @Html.ValidationMessageFor(model => model.Bloqueado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.ActionLink("Voltar", "Index", "Home", null, new { @class = "btn btn-info" })
                <input type="submit" value="Salvar" class="btn btn-success" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}